kind: pipeline
type: kubernetes
name: proxy-build-pipeline

platform:
  os: linux
  arch: amd64


steps:
  - name: docker  
    image: plugins/docker
    settings:
      repo: overmorrow/auth-es-proxy
      tags:
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
